version: '{build}'

branches:
  only:
    - master
    - /ci.*/
    - /stable.*/

skip_non_tags: true

image: Visual Studio 2017

init:
  - ps: $env:commit = $env:appveyor_repo_commit.SubString(0,8)

install:
  - ps: npm config set msvs_version 2017

build_script:
  - ps: mkdir ..\app
  - cmd: .\build.cmd

before_deploy:
  - ps: (Get-ChildItem -Force -Path ..\..\app).FullName
  - ps: (Get-ChildItem -Force -Path ..\..\app\dist).FullName
  - cmd: 7z -ttar a dummy ..\..\app\dist\*.dll ..\..\app\dist\*.pdb ..\..\app\dist\mailsync.exe -so | 7z -si -tgzip a .\mailsync.tar.gz
  - ps: Get-ChildItem .\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName "win-ia32/$($_.Name)" -DeploymentName s3-deployment }

deploy:
  - provider: S3
    name: s3-deployment
    access_key_id: AKIAJQWOM4SPSY3TXI5Q
    secret_access_key:
      secure: XlLzz7sdvrtgi4g459NvxLfrH/+hOutb+0Osz29unfi4Zcw9N8H8SEaq6m3ZeWc+
    region: us-east-1
    bucket: mailspring-builds
    folder: 'mailsync/$(commit)'
    set_public: true

# Stop Appveyor from "Discovering Tests" forever
test: off

environment:
  global:
    encrypted_faf2708e46e2_key:
      secure: mdegN/AldrADhtEop6mDwq6d4jUskzijK2X7Twf2lj9t3jdaW4OtMuJ5Ywyt+GN/N7qMFr7LOvxQ5gz4aoIW+Dg9d03AX3BH1o4BI6g+wdk=
    encrypted_faf2708e46e2_iv:
      secure: B2pwd1AlmQHjIpIau1NylfEMkwJJ5u7NhxgZcU8WicwP6+cmePnAacYIwpe1fXEf
